app: hi_fi_rush
-
go:                         user.game_move_dir_hold_w()
go left:                    user.game_move_dir_hold_a()
go right:                   user.game_move_dir_hold_d()
back:                       user.game_move_dir_hold_s()
step:                       user.game_move_dir_step_w()
step left:                  user.game_move_dir_step_a()
step right:                 user.game_move_dir_step_d()
step back:                  user.game_move_dir_step_s()
dog [go]:                   user.game_move_dir_toggle_w()
dog left:                   user.game_move_dir_toggle_a()
dog right:                  user.game_move_dir_toggle_d()
dog back:                   user.game_move_dir_toggle_s()
stopper:                    user.game_stopper()
turn left:                  user.game_turn_left_90()
turn right:                 user.game_turn_right_90()
turnaround:                 user.game_turn_180()
soft left:                  user.game_turn_left_15()
soft right:                 user.game_turn_right_15()
medium left:                user.game_turn_left_30()
medium right:               user.game_turn_right_30()
large left:                 user.game_turn_left_45()
large right:                user.game_turn_right_45()
