parrot(hiss):               user.manage('hiss')
parrot(hiss:stop):          user.manage('hiss_stop')
parrot(shush):              user.manage('shush')
parrot(shush:stop):         user.manage('shush_stop')
parrot(nn):                 user.manage('nn')
