head (set | reset):         user.head_triggered_actions_reset()
head start:                 user.head_triggered_actions_start()
head stop:                  user.head_triggered_actions_stop()
head show:                  user.head_triggered_actions_show_ui()
head hide:                  user.head_triggered_actions_hide_ui()
