parrot(cluck):              user.parrot_v5_mode_enable()
parrot oh right [click]:    user.parrot_v5_set_click_alternate("right")
parrot oh right drag:       user.parrot_v5_set_click_alternate("right_drag")
parrot oh mid [click]:      user.parrot_v5_set_click_alternate("mid")
parrot oh mid drag:         user.parrot_v5_set_click_alternate("mid_drag")
